# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

baseURL = "https://cukoo-li.github.io/"
defaultContentLanguage = "zh-CN"
languageCode = "zh-CN"
theme = "congo"
publishDir = "docs"

enableRobotsTXT = true
paginate = 10
summaryLength = 0

[outputs]
home = ["HTML", "RSS", "JSON"]
