languageCode = "zh-cn"
languageName = "简体中文"
weight = 1
title = "Cukoo's Blog"

[params]
  displayName = "简体中文"
  isoCode = "zh-cn"
  rtl = false
  dateFormat = "2006-01-02"
#   logo = "img/blowfish_logo_transparent.png"
  description = "Cukoo's Blog"

[author]
  name = "Cukoo"
  image = "images/author.jpg"
  headline = "Practice makes perfect."
  bio = "黄色的树林里分出两条路，我选择了人迹更少的一条，从此决定了我一生的道路。"
  links = [
    { github = "https://github.com/Cukoo-Li" },
    { qq = "http://wpa.qq.com/msgrd?v=3&uin=891623879&site=qq:891623879&menu=yes" },
    { bilibili = "https://space.bilibili.com/354615868" },
  ]
