languageCode = "zh-CN"
languageName = "简体中文"
languageDirection = "ltr"
weight = 1

title = "Cukoo's Blog"
copyright = "Copyright &copy; 2024 Cukoo"

[params]
dateFormat = "2006年1月2日"

mainSections = ["posts"]
description = "Cukoo码字的地方"

[params.author]
bio = "一个想成为程序员的非科班研究生"
name = "Cukoo"
image = "images/Cukoo.jpg"
# headline = "I'm only human"

links = [
    { github = "https://github.com/Cukoo-Li" },
    { qq = "http://wpa.qq.com/msgrd?v=3&uin=891623879&site=qq:891623879&menu=yes" },
    { steam = "https://steamcommunity.com/profiles/76561199021822259/" },
]
